#!/bin/bash
printf "Ground truth level 0\n\n" 
printf "SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm\n" 
../nmi/onmi 0/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_first_level_50000_5.out
../nmi/onmi 1/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_first_level_50000_5.out
../nmi/onmi 2/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_first_level_50000_5.out
../nmi/onmi 3/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_first_level_50000_5.out
../nmi/onmi 4/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_first_level_50000_5.out
../nmi/onmi 5/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_first_level_50000_5.out
../nmi/onmi 6/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_first_level_50000_5.out
../nmi/onmi 7/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_first_level_50000_5.out
../nmi/onmi 8/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_first_level_50000_5.out
../nmi/onmi 9/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_first_level_50000_5.out
printf "SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm\n" 
../nmi/onmi 0/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_first_level_50000_8.out
../nmi/onmi 1/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_first_level_50000_8.out
../nmi/onmi 2/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_first_level_50000_8.out
../nmi/onmi 3/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_first_level_50000_8.out
../nmi/onmi 4/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_first_level_50000_8.out
../nmi/onmi 5/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_first_level_50000_8.out
../nmi/onmi 6/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_first_level_50000_8.out
../nmi/onmi 7/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_first_level_50000_8.out
../nmi/onmi 8/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_first_level_50000_8.out
../nmi/onmi 9/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_first_level_50000_8.out
printf "SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm\n" 
../nmi/onmi 0/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_first_level_50000_10.out
../nmi/onmi 1/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_first_level_50000_10.out
../nmi/onmi 2/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_first_level_50000_10.out
../nmi/onmi 3/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_first_level_50000_10.out
../nmi/onmi 4/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_first_level_50000_10.out
../nmi/onmi 5/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_first_level_50000_10.out
../nmi/onmi 6/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_first_level_50000_10.out
../nmi/onmi 7/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_first_level_50000_10.out
../nmi/onmi 8/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_first_level_50000_10.out
../nmi/onmi 9/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_first_level_50000_10.out
printf "SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm\n" 
../nmi/onmi 0/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_first_level_50000_13.out
../nmi/onmi 1/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_first_level_50000_13.out
../nmi/onmi 2/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_first_level_50000_13.out
../nmi/onmi 3/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_first_level_50000_13.out
../nmi/onmi 4/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_first_level_50000_13.out
../nmi/onmi 5/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_first_level_50000_13.out
../nmi/onmi 6/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_first_level_50000_13.out
../nmi/onmi 7/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_first_level_50000_13.out
../nmi/onmi 8/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_first_level_50000_13.out
../nmi/onmi 9/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_first_level_50000_13.out
printf "SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm\n" 
../nmi/onmi 0/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_first_level_50000_15.out
../nmi/onmi 1/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_first_level_50000_15.out
../nmi/onmi 2/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_first_level_50000_15.out
../nmi/onmi 3/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_first_level_50000_15.out
../nmi/onmi 4/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_first_level_50000_15.out
../nmi/onmi 5/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_first_level_50000_15.out
../nmi/onmi 6/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_first_level_50000_15.out
../nmi/onmi 7/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_first_level_50000_15.out
../nmi/onmi 8/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_first_level_50000_15.out
../nmi/onmi 9/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_first_level_50000_15.out
printf "SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm\n" 
../nmi/onmi 0/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_first_level_50000_18.out
../nmi/onmi 1/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_first_level_50000_18.out
../nmi/onmi 2/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_first_level_50000_18.out
../nmi/onmi 3/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_first_level_50000_18.out
../nmi/onmi 4/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_first_level_50000_18.out
../nmi/onmi 5/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_first_level_50000_18.out
../nmi/onmi 6/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_first_level_50000_18.out
../nmi/onmi 7/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_first_level_50000_18.out
../nmi/onmi 8/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_first_level_50000_18.out
../nmi/onmi 9/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_first_level_50000_18.out
printf "SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm\n" 
../nmi/onmi 0/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_first_level_50000_20.out
../nmi/onmi 1/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_first_level_50000_20.out
../nmi/onmi 2/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_first_level_50000_20.out
../nmi/onmi 3/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_first_level_50000_20.out
../nmi/onmi 4/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_first_level_50000_20.out
../nmi/onmi 5/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_first_level_50000_20.out
../nmi/onmi 6/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_first_level_50000_20.out
../nmi/onmi 7/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_first_level_50000_20.out
../nmi/onmi 8/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_first_level_50000_20.out
../nmi/onmi 9/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_first_level_50000_20.out
printf "Ground truth level 1\n\n" 
printf "SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm\n" 
../nmi/onmi 0/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_second_level_50000_5.out
../nmi/onmi 1/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_second_level_50000_5.out
../nmi/onmi 2/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_second_level_50000_5.out
../nmi/onmi 3/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_second_level_50000_5.out
../nmi/onmi 4/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_second_level_50000_5.out
../nmi/onmi 5/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_second_level_50000_5.out
../nmi/onmi 6/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_second_level_50000_5.out
../nmi/onmi 7/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_second_level_50000_5.out
../nmi/onmi 8/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_second_level_50000_5.out
../nmi/onmi 9/SLPAw_network_50000_5_run1_r0.15_v3_T100.icpm community_second_level_50000_5.out
printf "SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm\n" 
../nmi/onmi 0/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_second_level_50000_8.out
../nmi/onmi 1/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_second_level_50000_8.out
../nmi/onmi 2/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_second_level_50000_8.out
../nmi/onmi 3/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_second_level_50000_8.out
../nmi/onmi 4/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_second_level_50000_8.out
../nmi/onmi 5/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_second_level_50000_8.out
../nmi/onmi 6/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_second_level_50000_8.out
../nmi/onmi 7/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_second_level_50000_8.out
../nmi/onmi 8/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_second_level_50000_8.out
../nmi/onmi 9/SLPAw_network_50000_8_run1_r0.15_v3_T100.icpm community_second_level_50000_8.out
printf "SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm\n" 
../nmi/onmi 0/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_second_level_50000_10.out
../nmi/onmi 1/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_second_level_50000_10.out
../nmi/onmi 2/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_second_level_50000_10.out
../nmi/onmi 3/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_second_level_50000_10.out
../nmi/onmi 4/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_second_level_50000_10.out
../nmi/onmi 5/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_second_level_50000_10.out
../nmi/onmi 6/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_second_level_50000_10.out
../nmi/onmi 7/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_second_level_50000_10.out
../nmi/onmi 8/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_second_level_50000_10.out
../nmi/onmi 9/SLPAw_network_50000_10_run1_r0.15_v3_T100.icpm community_second_level_50000_10.out
printf "SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm\n" 
../nmi/onmi 0/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_second_level_50000_13.out
../nmi/onmi 1/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_second_level_50000_13.out
../nmi/onmi 2/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_second_level_50000_13.out
../nmi/onmi 3/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_second_level_50000_13.out
../nmi/onmi 4/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_second_level_50000_13.out
../nmi/onmi 5/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_second_level_50000_13.out
../nmi/onmi 6/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_second_level_50000_13.out
../nmi/onmi 7/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_second_level_50000_13.out
../nmi/onmi 8/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_second_level_50000_13.out
../nmi/onmi 9/SLPAw_network_50000_13_run1_r0.15_v3_T100.icpm community_second_level_50000_13.out
printf "SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm\n" 
../nmi/onmi 0/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_second_level_50000_15.out
../nmi/onmi 1/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_second_level_50000_15.out
../nmi/onmi 2/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_second_level_50000_15.out
../nmi/onmi 3/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_second_level_50000_15.out
../nmi/onmi 4/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_second_level_50000_15.out
../nmi/onmi 5/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_second_level_50000_15.out
../nmi/onmi 6/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_second_level_50000_15.out
../nmi/onmi 7/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_second_level_50000_15.out
../nmi/onmi 8/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_second_level_50000_15.out
../nmi/onmi 9/SLPAw_network_50000_15_run1_r0.15_v3_T100.icpm community_second_level_50000_15.out
printf "SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm\n" 
../nmi/onmi 0/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_second_level_50000_18.out
../nmi/onmi 1/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_second_level_50000_18.out
../nmi/onmi 2/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_second_level_50000_18.out
../nmi/onmi 3/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_second_level_50000_18.out
../nmi/onmi 4/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_second_level_50000_18.out
../nmi/onmi 5/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_second_level_50000_18.out
../nmi/onmi 6/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_second_level_50000_18.out
../nmi/onmi 7/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_second_level_50000_18.out
../nmi/onmi 8/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_second_level_50000_18.out
../nmi/onmi 9/SLPAw_network_50000_18_run1_r0.15_v3_T100.icpm community_second_level_50000_18.out
printf "SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm\n" 
../nmi/onmi 0/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_second_level_50000_20.out
../nmi/onmi 1/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_second_level_50000_20.out
../nmi/onmi 2/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_second_level_50000_20.out
../nmi/onmi 3/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_second_level_50000_20.out
../nmi/onmi 4/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_second_level_50000_20.out
../nmi/onmi 5/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_second_level_50000_20.out
../nmi/onmi 6/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_second_level_50000_20.out
../nmi/onmi 7/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_second_level_50000_20.out
../nmi/onmi 8/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_second_level_50000_20.out
../nmi/onmi 9/SLPAw_network_50000_20_run1_r0.15_v3_T100.icpm community_second_level_50000_20.out
